apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: api-de-somas
  name: api-de-somas
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: api-de-somas
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-de-somas
    spec:
      containers:
      - image: gcr.io/gke-api-de-somas-default-pool-cd2114f9-x6jr/api-de-somas
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        name: api-de-somas
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
